name: 'succutio '
favicon: null
layout_spectrum: 0.7332006921060383
typography_spectrum: 0.7725801861379296
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3349101049825549
  lightness: 0.8413302153348923
  saturation: 0.6041284387465566
  rhythmicContrast: 0.4285524857696146
purpose: []
